-- ============================================================
-- FEP_TRANSACTION - Transaction Records
-- ============================================================

-- Connect to FREEPDB1 as fep_user
CONNECT fep_user/fep_password@//localhost:1521/FREEPDB1

CREATE TABLE FEP_TRANSACTION (
    ID                      NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRANSACTION_ID          VARCHAR2(64) NOT NULL,
    TRANSACTION_TYPE        VARCHAR2(32) NOT NULL,
    PROCESSING_CODE         VARCHAR2(6),
    MASKED_PAN              VARCHAR2(19),
    PAN                     VARCHAR2(64),
    PAN_HASH                VARCHAR2(64),
    AMOUNT                  NUMBER(18,2),
    CURRENCY_CODE           VARCHAR2(3) DEFAULT '901',
    SOURCE_ACCOUNT          VARCHAR2(32),
    DESTINATION_ACCOUNT     VARCHAR2(32),
    DESTINATION_BANK_CODE   VARCHAR2(7),
    TERMINAL_ID             VARCHAR2(16),
    MERCHANT_ID             VARCHAR2(15),
    ACQUIRING_BANK_CODE     VARCHAR2(7),
    STAN                    VARCHAR2(6),
    RRN                     VARCHAR2(12),
    CHANNEL                 VARCHAR2(16),
    STATUS                  VARCHAR2(32) NOT NULL,
    RESPONSE_CODE           VARCHAR2(4),
    AUTHORIZATION_CODE      VARCHAR2(6),
    HOST_REFERENCE_NUMBER   VARCHAR2(32),
    ORIGINAL_TRANSACTION_ID VARCHAR2(64),
    REQUEST_TIME            TIMESTAMP(6),
    TRANSACTION_TIME        TIMESTAMP(6),
    RESPONSE_TIME           TIMESTAMP(6),
    PROCESSING_TIME_MS      NUMBER(10),
    ERROR_DETAILS           VARCHAR2(500),
    CREATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    TRANSACTION_DATE        VARCHAR2(10) NOT NULL,
    CONSTRAINT UK_FEP_TXN_ID UNIQUE (TRANSACTION_ID)
);

CREATE INDEX IDX_FEP_TXN_RRN_STAN ON FEP_TRANSACTION(RRN, STAN);
CREATE INDEX IDX_FEP_TXN_MASKED_PAN ON FEP_TRANSACTION(MASKED_PAN, REQUEST_TIME);
CREATE INDEX IDX_FEP_TXN_TERMINAL ON FEP_TRANSACTION(TERMINAL_ID, REQUEST_TIME);
CREATE INDEX IDX_FEP_TXN_STATUS ON FEP_TRANSACTION(STATUS, TRANSACTION_DATE);
CREATE INDEX IDX_FEP_TXN_RRN_STAN_TERM ON FEP_TRANSACTION(RRN, STAN, TERMINAL_ID);
CREATE INDEX IDX_FEP_TXN_ORIGINAL ON FEP_TRANSACTION(ORIGINAL_TRANSACTION_ID);
CREATE INDEX IDX_FEP_TXN_DATE ON FEP_TRANSACTION(TRANSACTION_DATE);

COMMENT ON TABLE FEP_TRANSACTION IS 'FEP transaction records for FISC interbank operations';
COMMENT ON COLUMN FEP_TRANSACTION.TRANSACTION_ID IS 'Unique transaction identifier';
COMMENT ON COLUMN FEP_TRANSACTION.STAN IS 'System Trace Audit Number (ISO 8583 Field 11)';
COMMENT ON COLUMN FEP_TRANSACTION.RRN IS 'Retrieval Reference Number (ISO 8583 Field 37)';
COMMENT ON COLUMN FEP_TRANSACTION.TRANSACTION_DATE IS 'Transaction date in YYYY-MM-DD format for partitioning';
