-- ============================================================
-- FEP_SCHEDULED_TRANSFER - Scheduled Transfers
-- ============================================================

-- Connect to FREEPDB1 as fep_user
CONNECT fep_user/fep_password@//localhost:1521/FREEPDB1

CREATE TABLE FEP_SCHEDULED_TRANSFER (
    SCHEDULE_ID             VARCHAR2(32) PRIMARY KEY,
    SOURCE_ACCOUNT          VARCHAR2(32) NOT NULL,
    DESTINATION_ACCOUNT     VARCHAR2(32) NOT NULL,
    DESTINATION_BANK_CODE   VARCHAR2(7) NOT NULL,
    AMOUNT                  NUMBER(18,2) NOT NULL,
    CURRENCY_CODE           VARCHAR2(3) DEFAULT '901',
    SCHEDULED_DATE          DATE NOT NULL,
    RECURRENCE_TYPE         VARCHAR2(10) DEFAULT 'ONE_TIME',
    END_DATE                DATE,
    REMAINING_EXECUTIONS    NUMBER(5),
    MEMO                    VARCHAR2(200),
    STATUS                  VARCHAR2(20) NOT NULL,
    CUSTOMER_ID             VARCHAR2(32) NOT NULL,
    CHANNEL                 VARCHAR2(16),
    CREATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP(6),
    LAST_EXECUTED_AT        TIMESTAMP(6),
    LAST_EXECUTION_RESULT   VARCHAR2(500),
    SUCCESSFUL_EXECUTIONS   NUMBER(10) DEFAULT 0,
    FAILED_EXECUTIONS       NUMBER(10) DEFAULT 0
);

CREATE INDEX IDX_SCH_TXF_CUSTOMER ON FEP_SCHEDULED_TRANSFER(CUSTOMER_ID);
CREATE INDEX IDX_SCH_TXF_STATUS_DATE ON FEP_SCHEDULED_TRANSFER(STATUS, SCHEDULED_DATE);
CREATE INDEX IDX_SCH_TXF_READY ON FEP_SCHEDULED_TRANSFER(SCHEDULED_DATE, STATUS);

COMMENT ON TABLE FEP_SCHEDULED_TRANSFER IS 'Scheduled transfer records';
COMMENT ON COLUMN FEP_SCHEDULED_TRANSFER.RECURRENCE_TYPE IS 'ONE_TIME, DAILY, WEEKLY, MONTHLY';
COMMENT ON COLUMN FEP_SCHEDULED_TRANSFER.STATUS IS 'PENDING, ACTIVE, COMPLETED, FAILED, CANCELLED, SUSPENDED';
