-- ============================================================
-- FEP_SETTLEMENT_FILE - Settlement Files
-- ============================================================

-- Connect to FREEPDB1 as fep_user
CONNECT fep_user/fep_password@//localhost:1521/FREEPDB1

CREATE TABLE FEP_SETTLEMENT_FILE (
    FILE_ID                 VARCHAR2(32) PRIMARY KEY,
    FILE_NAME               VARCHAR2(255) NOT NULL,
    SETTLEMENT_DATE         DATE NOT NULL,
    FILE_TYPE               VARCHAR2(20) NOT NULL,
    SOURCE                  VARCHAR2(32),
    BANK_CODE               VARCHAR2(7),
    PROCESSING_STATUS       VARCHAR2(40) NOT NULL,
    RECEIVED_AT             TIMESTAMP(6),
    PROCESSING_STARTED_AT   TIMESTAMP(6),
    PROCESSING_COMPLETED_AT TIMESTAMP(6),
    ERROR_MESSAGE           VARCHAR2(1000),
    CHECKSUM                VARCHAR2(64),
    FILE_SIZE_BYTES         NUMBER(15),
    HEADER_VERSION          VARCHAR2(10),
    HEADER_CREATION_DATE    DATE,
    HEADER_CREATING_BANK    VARCHAR2(7),
    HEADER_RECEIVING_BANK   VARCHAR2(7),
    HEADER_FILE_TYPE        VARCHAR2(20),
    HEADER_RAW              CLOB,
    TRAILER_RECORD_COUNT    NUMBER(10),
    TRAILER_TOTAL_AMOUNT    NUMBER(18,2),
    TRAILER_DEBIT_AMOUNT    NUMBER(18,2),
    TRAILER_CREDIT_AMOUNT   NUMBER(18,2),
    TRAILER_DEBIT_COUNT     NUMBER(10),
    TRAILER_CREDIT_COUNT    NUMBER(10),
    TRAILER_CHECKSUM        VARCHAR2(64),
    TRAILER_RAW             CLOB,
    CREATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_STLMT_FILE_DATE ON FEP_SETTLEMENT_FILE(SETTLEMENT_DATE);
CREATE INDEX IDX_STLMT_FILE_STATUS ON FEP_SETTLEMENT_FILE(PROCESSING_STATUS);
CREATE INDEX IDX_STLMT_FILE_DATE_RANGE ON FEP_SETTLEMENT_FILE(SETTLEMENT_DATE, PROCESSING_STATUS);

COMMENT ON TABLE FEP_SETTLEMENT_FILE IS 'Settlement files received from FISC';
COMMENT ON COLUMN FEP_SETTLEMENT_FILE.FILE_TYPE IS 'DAILY, MONTHLY, AD_HOC';
COMMENT ON COLUMN FEP_SETTLEMENT_FILE.PROCESSING_STATUS IS 'RECEIVED, VALIDATING, PARSING, RECONCILING, COMPLETED, FAILED';
