-- ============================================================
-- FEP_SETTLEMENT_RECORD - Settlement Records
-- ============================================================

-- Connect to FREEPDB1 as fep_user
CONNECT fep_user/fep_password@//localhost:1521/FREEPDB1

CREATE TABLE FEP_SETTLEMENT_RECORD (
    SEQUENCE_NUMBER         NUMBER(15) NOT NULL,
    FILE_ID                 VARCHAR2(32) NOT NULL,
    SETTLEMENT_DATE         DATE NOT NULL,
    TRANSACTION_REF_NO      VARCHAR2(64) NOT NULL,
    STAN                    VARCHAR2(6),
    RRN                     VARCHAR2(12),
    TRANSACTION_TYPE        VARCHAR2(32),
    TRANSACTION_CODE        VARCHAR2(10),
    ACQUIRING_BANK_CODE     VARCHAR2(7),
    ISSUING_BANK_CODE       VARCHAR2(7),
    CARD_NUMBER             VARCHAR2(64),
    AMOUNT                  NUMBER(18,2),
    CURRENCY_CODE           VARCHAR2(3),
    FEE_AMOUNT              NUMBER(18,2),
    NET_AMOUNT              NUMBER(18,2),
    TRANSACTION_DATE_TIME   TIMESTAMP(6),
    STATUS                  VARCHAR2(32) NOT NULL,
    TERMINAL_ID             VARCHAR2(16),
    MERCHANT_ID             VARCHAR2(15),
    AUTH_CODE               VARCHAR2(6),
    RESPONSE_CODE           VARCHAR2(4),
    IS_REVERSAL             NUMBER(1) DEFAULT 0,
    ORIGINAL_TRANSACTION_REF VARCHAR2(64),
    CHANNEL                 VARCHAR2(16),
    FROM_ACCOUNT            VARCHAR2(32),
    TO_ACCOUNT              VARCHAR2(32),
    RECORD_HASH             VARCHAR2(64),
    RAW_DATA                CLOB,
    NOTES                   VARCHAR2(500),
    MATCHED_TRANSACTION_ID  VARCHAR2(64),
    MATCHED_AT              TIMESTAMP(6),
    CONSTRAINT PK_STLMT_REC PRIMARY KEY (FILE_ID, SEQUENCE_NUMBER),
    CONSTRAINT FK_STLMT_REC_FILE FOREIGN KEY (FILE_ID)
        REFERENCES FEP_SETTLEMENT_FILE(FILE_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_STLMT_REC_REF ON FEP_SETTLEMENT_RECORD(TRANSACTION_REF_NO);
CREATE INDEX IDX_STLMT_REC_STATUS ON FEP_SETTLEMENT_RECORD(STATUS);
CREATE INDEX IDX_STLMT_REC_DATE ON FEP_SETTLEMENT_RECORD(SETTLEMENT_DATE, STATUS);
CREATE INDEX IDX_STLMT_REC_MATCHED ON FEP_SETTLEMENT_RECORD(MATCHED_TRANSACTION_ID);
CREATE INDEX IDX_STLMT_REC_RRN_STAN ON FEP_SETTLEMENT_RECORD(RRN, STAN);

COMMENT ON TABLE FEP_SETTLEMENT_RECORD IS 'Individual settlement records from FISC files';
COMMENT ON COLUMN FEP_SETTLEMENT_RECORD.STATUS IS 'PENDING, MATCHED, AMOUNT_MISMATCH, NOT_FOUND, DUPLICATE, etc.';
