-- ============================================================
-- FEP_DISCREPANCY - Discrepancy Records
-- ============================================================

-- Connect to FREEPDB1 as fep_user
CONNECT fep_user/fep_password@//localhost:1521/FREEPDB1

CREATE TABLE FEP_DISCREPANCY (
    DISCREPANCY_ID          VARCHAR2(32) PRIMARY KEY,
    DISCREPANCY_TYPE        VARCHAR2(32) NOT NULL,
    SETTLEMENT_DATE         DATE NOT NULL,
    SETTLEMENT_FILE_ID      VARCHAR2(32),
    SETTLEMENT_RECORD_REF   VARCHAR2(64),
    INTERNAL_TRANSACTION_REF VARCHAR2(64),
    SETTLEMENT_AMOUNT       NUMBER(18,2),
    INTERNAL_AMOUNT         NUMBER(18,2),
    DIFFERENCE_AMOUNT       NUMBER(18,2),
    CURRENCY_CODE           VARCHAR2(3),
    CARD_NUMBER             VARCHAR2(64),
    TRANSACTION_TYPE        VARCHAR2(32),
    STATUS                  VARCHAR2(32) NOT NULL,
    PRIORITY                VARCHAR2(20) NOT NULL,
    DESCRIPTION             VARCHAR2(1000),
    ROOT_CAUSE              VARCHAR2(1000),
    RESOLUTION_NOTES        VARCHAR2(2000),
    RESOLUTION_ACTION       VARCHAR2(32),
    ASSIGNED_TO             VARCHAR2(64),
    CREATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP(6),
    RESOLVED_AT             TIMESTAMP(6),
    RESOLVED_BY             VARCHAR2(64),
    INVESTIGATION_NOTES     CLOB,
    RELATED_DISCREPANCIES   VARCHAR2(1000),
    CONSTRAINT FK_DISC_FILE FOREIGN KEY (SETTLEMENT_FILE_ID)
        REFERENCES FEP_SETTLEMENT_FILE(FILE_ID) ON DELETE SET NULL
);

CREATE INDEX IDX_DISC_DATE ON FEP_DISCREPANCY(SETTLEMENT_DATE);
CREATE INDEX IDX_DISC_STATUS ON FEP_DISCREPANCY(STATUS);
CREATE INDEX IDX_DISC_TYPE ON FEP_DISCREPANCY(DISCREPANCY_TYPE);
CREATE INDEX IDX_DISC_PRIORITY ON FEP_DISCREPANCY(PRIORITY);
CREATE INDEX IDX_DISC_ASSIGNED ON FEP_DISCREPANCY(ASSIGNED_TO, STATUS);

COMMENT ON TABLE FEP_DISCREPANCY IS 'Discrepancies found during settlement reconciliation';
COMMENT ON COLUMN FEP_DISCREPANCY.DISCREPANCY_TYPE IS 'AMOUNT_MISMATCH, MISSING_IN_SETTLEMENT, MISSING_IN_INTERNAL, DUPLICATE, STATUS_MISMATCH';
COMMENT ON COLUMN FEP_DISCREPANCY.STATUS IS 'OPEN, INVESTIGATING, PENDING_APPROVAL, RESOLVED, WRITTEN_OFF, ESCALATED, CLOSED';
COMMENT ON COLUMN FEP_DISCREPANCY.PRIORITY IS 'HIGH, MEDIUM, LOW';
COMMENT ON COLUMN FEP_DISCREPANCY.INVESTIGATION_NOTES IS 'JSON array of investigation notes';
