-- ============================================================
-- FEP_CLEARING_RECORD - Clearing Records
-- ============================================================

-- Connect to FREEPDB1 as fep_user
CONNECT fep_user/fep_password@//localhost:1521/FREEPDB1

CREATE TABLE FEP_CLEARING_RECORD (
    CLEARING_ID             VARCHAR2(32) PRIMARY KEY,
    SETTLEMENT_DATE         DATE NOT NULL,
    BATCH_NUMBER            VARCHAR2(20),
    OUR_BANK_CODE           VARCHAR2(7) NOT NULL,
    COUNTERPARTY_BANK_CODE  VARCHAR2(7) NOT NULL,
    TRANSACTION_CATEGORY    VARCHAR2(32),
    DEBIT_COUNT             NUMBER(10) DEFAULT 0,
    DEBIT_AMOUNT            NUMBER(18,2) DEFAULT 0,
    CREDIT_COUNT            NUMBER(10) DEFAULT 0,
    CREDIT_AMOUNT           NUMBER(18,2) DEFAULT 0,
    NET_AMOUNT              NUMBER(18,2),
    FEE_AMOUNT              NUMBER(18,2),
    CURRENCY_CODE           VARCHAR2(3) DEFAULT 'TWD',
    STATUS                  VARCHAR2(20) NOT NULL,
    CREATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONFIRMED_AT            TIMESTAMP(6),
    SETTLED_AT              TIMESTAMP(6),
    CONFIRMED_BY            VARCHAR2(64),
    NOTES                   VARCHAR2(500),
    SETTLEMENT_FILE_ID      VARCHAR2(32),
    CONSTRAINT FK_CLR_FILE FOREIGN KEY (SETTLEMENT_FILE_ID)
        REFERENCES FEP_SETTLEMENT_FILE(FILE_ID) ON DELETE SET NULL
);

CREATE INDEX IDX_CLR_DATE ON FEP_CLEARING_RECORD(SETTLEMENT_DATE);
CREATE INDEX IDX_CLR_STATUS ON FEP_CLEARING_RECORD(STATUS);
CREATE INDEX IDX_CLR_COUNTERPARTY ON FEP_CLEARING_RECORD(COUNTERPARTY_BANK_CODE);
CREATE INDEX IDX_CLR_OUR_BANK ON FEP_CLEARING_RECORD(OUR_BANK_CODE, SETTLEMENT_DATE);

COMMENT ON TABLE FEP_CLEARING_RECORD IS 'Net clearing amounts between banks';
COMMENT ON COLUMN FEP_CLEARING_RECORD.NET_AMOUNT IS 'Positive=we receive, Negative=we pay';
COMMENT ON COLUMN FEP_CLEARING_RECORD.STATUS IS 'PENDING, CALCULATED, CONFIRMED, SUBMITTED, SETTLING, SETTLED, FAILED, CANCELLED';
