-- ============================================================
-- FEP_TRANSACTION - Add fields for High TPS Architecture
-- ============================================================
-- 支援 Request/Response 分離式 BPMN + Redis + DB 架構
-- ============================================================

-- Connect to FREEPDB1 as fep_user
CONNECT fep_user/fep_password@//localhost:1521/FREEPDB1

-- 新增 MTI 欄位 (Message Type Indicator)
ALTER TABLE FEP_TRANSACTION ADD MTI VARCHAR2(4);
COMMENT ON COLUMN FEP_TRANSACTION.MTI IS 'Message Type Indicator (e.g., 0200, 0210, 0400)';

-- 新增來源銀行代碼 (與 ACQUIRING_BANK_CODE 區分)
ALTER TABLE FEP_TRANSACTION ADD SOURCE_BANK_CODE VARCHAR2(7);
COMMENT ON COLUMN FEP_TRANSACTION.SOURCE_BANK_CODE IS 'Source bank code for transfer transactions';

-- 新增目標銀行代碼 (與 DESTINATION_BANK_CODE 同義，保持一致性)
ALTER TABLE FEP_TRANSACTION ADD TARGET_BANK_CODE VARCHAR2(7);
COMMENT ON COLUMN FEP_TRANSACTION.TARGET_BANK_CODE IS 'Target bank code for transfer transactions';

-- 新增過期時間 (用於 timeout 掃描)
ALTER TABLE FEP_TRANSACTION ADD EXPIRE_TIME TIMESTAMP(6);
COMMENT ON COLUMN FEP_TRANSACTION.EXPIRE_TIME IS 'Transaction expire time for timeout scanning';

-- 新增發送至 FISC 時間
ALTER TABLE FEP_TRANSACTION ADD SENT_TO_FISC_TIME TIMESTAMP(6);
COMMENT ON COLUMN FEP_TRANSACTION.SENT_TO_FISC_TIME IS 'Time when request was sent to FISC';

-- 新增 FISC 回應時間
ALTER TABLE FEP_TRANSACTION ADD FISC_RESPONSE_TIME TIMESTAMP(6);
COMMENT ON COLUMN FEP_TRANSACTION.FISC_RESPONSE_TIME IS 'Time when response was received from FISC';

-- 新增原始請求電文 (CLOB)
ALTER TABLE FEP_TRANSACTION ADD RAW_REQUEST CLOB;
COMMENT ON COLUMN FEP_TRANSACTION.RAW_REQUEST IS 'Raw request message in Base64 encoding';

-- 新增原始回應電文 (CLOB)
ALTER TABLE FEP_TRANSACTION ADD RAW_RESPONSE CLOB;
COMMENT ON COLUMN FEP_TRANSACTION.RAW_RESPONSE IS 'Raw response message in Base64 encoding';

-- 新增 BPMN Process ID
ALTER TABLE FEP_TRANSACTION ADD PROCESS_ID VARCHAR2(64);
COMMENT ON COLUMN FEP_TRANSACTION.PROCESS_ID IS 'Camunda BPMN process instance ID';

-- 新增通道 ID
ALTER TABLE FEP_TRANSACTION ADD CHANNEL_ID VARCHAR2(32);
COMMENT ON COLUMN FEP_TRANSACTION.CHANNEL_ID IS 'Channel identifier (e.g., ATM_001, POS_002)';

-- 新增沖正狀態
ALTER TABLE FEP_TRANSACTION ADD REVERSAL_STATUS VARCHAR2(20);
COMMENT ON COLUMN FEP_TRANSACTION.REVERSAL_STATUS IS 'Reversal status: NONE, IN_PROGRESS, SUCCESS, FAILED, PENDING_ADJUSTMENT';

-- 新增 Callback Key (用於關聯回應)
ALTER TABLE FEP_TRANSACTION ADD CALLBACK_KEY VARCHAR2(128);
COMMENT ON COLUMN FEP_TRANSACTION.CALLBACK_KEY IS 'Callback key for response correlation';

-- 建立 STATUS + EXPIRE_TIME 索引 (用於 timeout 掃描)
CREATE INDEX IDX_FEP_TXN_STATUS_EXPIRE ON FEP_TRANSACTION(STATUS, EXPIRE_TIME);

-- 建立 PROCESS_ID 索引
CREATE INDEX IDX_FEP_TXN_PROCESS_ID ON FEP_TRANSACTION(PROCESS_ID);

-- 建立 CHANNEL_ID + STAN 索引
CREATE INDEX IDX_FEP_TXN_CHANNEL_STAN ON FEP_TRANSACTION(CHANNEL_ID, STAN);

COMMIT;
