-- ============================================================
-- FEP_TRANSACTION_LOG - Transaction Audit Logs
-- ============================================================
-- 記錄交易處理過程的詳細日誌，用於稽核追蹤和問題分析
-- ============================================================

-- Connect to FREEPDB1 as fep_user
CONNECT fep_user/fep_password@//localhost:1521/FREEPDB1

-- Create sequence
CREATE SEQUENCE SEQ_FEP_TRANSACTION_LOG
    START WITH 1
    INCREMENT BY 50
    NOCACHE
    NOCYCLE;

-- Create table
CREATE TABLE FEP_TRANSACTION_LOG (
    ID                  NUMBER(19) DEFAULT SEQ_FEP_TRANSACTION_LOG.NEXTVAL PRIMARY KEY,
    TRANSACTION_ID      VARCHAR2(64) NOT NULL,
    STAN                VARCHAR2(6),
    LOG_STAGE           VARCHAR2(30) NOT NULL,
    LOG_LEVEL           VARCHAR2(10) NOT NULL,
    MESSAGE             VARCHAR2(500),
    DETAILS             CLOB,
    RAW_MESSAGE         CLOB,
    COMPONENT           VARCHAR2(100),
    DURATION_MS         NUMBER(10),
    ERROR_CODE          VARCHAR2(20),
    ERROR_MESSAGE       CLOB,
    SERVER_INSTANCE     VARCHAR2(50),
    LOG_TIME            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    LOG_DATE            VARCHAR2(10) NOT NULL
);

-- Create indexes
CREATE INDEX IDX_FEP_TXN_LOG_TXN_ID ON FEP_TRANSACTION_LOG(TRANSACTION_ID);
CREATE INDEX IDX_FEP_TXN_LOG_STAN ON FEP_TRANSACTION_LOG(STAN);
CREATE INDEX IDX_FEP_TXN_LOG_TIME ON FEP_TRANSACTION_LOG(LOG_TIME);
CREATE INDEX IDX_FEP_TXN_LOG_DATE ON FEP_TRANSACTION_LOG(LOG_DATE);
CREATE INDEX IDX_FEP_TXN_LOG_LEVEL_DATE ON FEP_TRANSACTION_LOG(LOG_LEVEL, LOG_DATE);
CREATE INDEX IDX_FEP_TXN_LOG_STAGE_DATE ON FEP_TRANSACTION_LOG(LOG_STAGE, LOG_DATE);

-- Add comments
COMMENT ON TABLE FEP_TRANSACTION_LOG IS 'Transaction audit logs for tracking and troubleshooting';
COMMENT ON COLUMN FEP_TRANSACTION_LOG.TRANSACTION_ID IS 'Related transaction ID';
COMMENT ON COLUMN FEP_TRANSACTION_LOG.STAN IS 'System Trace Audit Number';
COMMENT ON COLUMN FEP_TRANSACTION_LOG.LOG_STAGE IS 'Processing stage: REQUEST_RECEIVED, VALIDATION, LIMIT_CHECK, FREEZE_AMOUNT, MESSAGE_ASSEMBLY, SEND_TO_FISC, WAITING_RESPONSE, RESPONSE_RECEIVED, RESPONSE_PROCESSING, CONFIRM_DEBIT, UNFREEZE_AMOUNT, SEND_REVERSAL, REVERSAL_RESPONSE, REPLY_TO_CLIENT, COMPLETED, ERROR';
COMMENT ON COLUMN FEP_TRANSACTION_LOG.LOG_LEVEL IS 'Log level: DEBUG, INFO, WARN, ERROR';
COMMENT ON COLUMN FEP_TRANSACTION_LOG.MESSAGE IS 'Log message';
COMMENT ON COLUMN FEP_TRANSACTION_LOG.DETAILS IS 'Detailed information in JSON format';
COMMENT ON COLUMN FEP_TRANSACTION_LOG.RAW_MESSAGE IS 'Raw message in Base64 encoding';
COMMENT ON COLUMN FEP_TRANSACTION_LOG.COMPONENT IS 'Processing component name (e.g., Delegate name)';
COMMENT ON COLUMN FEP_TRANSACTION_LOG.DURATION_MS IS 'Processing duration in milliseconds';
COMMENT ON COLUMN FEP_TRANSACTION_LOG.ERROR_CODE IS 'Error code if applicable';
COMMENT ON COLUMN FEP_TRANSACTION_LOG.ERROR_MESSAGE IS 'Error message if applicable';
COMMENT ON COLUMN FEP_TRANSACTION_LOG.SERVER_INSTANCE IS 'Server instance ID';
COMMENT ON COLUMN FEP_TRANSACTION_LOG.LOG_TIME IS 'Log timestamp';
COMMENT ON COLUMN FEP_TRANSACTION_LOG.LOG_DATE IS 'Log date in yyyyMMdd format for partitioning';

COMMIT;
