-- ============================================================
-- FEP_REVERSAL - Reversal Transaction Records
-- ============================================================
-- 記錄沖正交易的詳細資訊，支援多次沖正重試追蹤
-- ============================================================

-- Connect to FREEPDB1 as fep_user
CONNECT fep_user/fep_password@//localhost:1521/FREEPDB1

-- Create sequence
CREATE SEQUENCE SEQ_FEP_REVERSAL
    START WITH 1
    INCREMENT BY 50
    NOCACHE
    NOCYCLE;

-- Create table
CREATE TABLE FEP_REVERSAL (
    ID                          NUMBER(19) DEFAULT SEQ_FEP_REVERSAL.NEXTVAL PRIMARY KEY,
    REVERSAL_ID                 VARCHAR2(64) NOT NULL,
    ORIGINAL_TRANSACTION_ID     VARCHAR2(64) NOT NULL,
    ORIGINAL_STAN               VARCHAR2(6) NOT NULL,
    ORIGINAL_MTI                VARCHAR2(4) NOT NULL,
    REVERSAL_STAN               VARCHAR2(6) NOT NULL,
    AMOUNT                      NUMBER(15,2) NOT NULL,
    REASON                      VARCHAR2(30) NOT NULL,
    STATUS                      VARCHAR2(20) NOT NULL,
    RESPONSE_CODE               VARCHAR2(4),
    RETRY_COUNT                 NUMBER(5) DEFAULT 0 NOT NULL,
    MAX_RETRY                   NUMBER(5) DEFAULT 3 NOT NULL,
    NEXT_RETRY_TIME             TIMESTAMP(6),
    SOURCE_ACCOUNT              VARCHAR2(32),
    TARGET_ACCOUNT              VARCHAR2(32),
    SOURCE_BANK_CODE            VARCHAR2(10),
    TARGET_BANK_CODE            VARCHAR2(10),
    CHANNEL_ID                  VARCHAR2(32),
    RAW_REQUEST                 CLOB,
    RAW_RESPONSE                CLOB,
    REMARK                      VARCHAR2(500),
    MANUAL_PROCESSING           NUMBER(1) DEFAULT 0 NOT NULL,
    PROCESSED_BY                VARCHAR2(50),
    PROCESSED_TIME              TIMESTAMP(6),
    CREATED_AT                  TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT                  TIMESTAMP(6),
    REVERSAL_DATE               VARCHAR2(10) NOT NULL,
    VERSION                     NUMBER(19) DEFAULT 0,
    CONSTRAINT UK_FEP_REV_ID UNIQUE (REVERSAL_ID)
);

-- Create indexes
CREATE INDEX IDX_FEP_REV_ORIG_TXN_ID ON FEP_REVERSAL(ORIGINAL_TRANSACTION_ID);
CREATE INDEX IDX_FEP_REV_ORIG_STAN ON FEP_REVERSAL(ORIGINAL_STAN);
CREATE INDEX IDX_FEP_REV_STATUS ON FEP_REVERSAL(STATUS);
CREATE INDEX IDX_FEP_REV_DATE ON FEP_REVERSAL(REVERSAL_DATE);
CREATE INDEX IDX_FEP_REV_RETRY ON FEP_REVERSAL(STATUS, RETRY_COUNT, NEXT_RETRY_TIME);

-- Add comments
COMMENT ON TABLE FEP_REVERSAL IS 'Reversal transaction records with retry tracking';
COMMENT ON COLUMN FEP_REVERSAL.REVERSAL_ID IS 'Unique reversal transaction ID (UUID)';
COMMENT ON COLUMN FEP_REVERSAL.ORIGINAL_TRANSACTION_ID IS 'Original transaction ID to be reversed';
COMMENT ON COLUMN FEP_REVERSAL.ORIGINAL_STAN IS 'Original STAN';
COMMENT ON COLUMN FEP_REVERSAL.ORIGINAL_MTI IS 'Original MTI (usually 0200)';
COMMENT ON COLUMN FEP_REVERSAL.REVERSAL_STAN IS 'Reversal STAN (0400 message)';
COMMENT ON COLUMN FEP_REVERSAL.AMOUNT IS 'Reversal amount';
COMMENT ON COLUMN FEP_REVERSAL.REASON IS 'Reversal reason: TIMEOUT, COMMUNICATION_FAILURE, SYSTEM_ERROR, CUSTOMER_CANCEL, DUPLICATE_TRANSACTION, VALIDATION_FAILURE, MANUAL';
COMMENT ON COLUMN FEP_REVERSAL.STATUS IS 'Reversal status: PENDING, IN_PROGRESS, SENT, SUCCESS, FAILED, PENDING_MANUAL, MANUAL_COMPLETED';
COMMENT ON COLUMN FEP_REVERSAL.RESPONSE_CODE IS 'FISC response code';
COMMENT ON COLUMN FEP_REVERSAL.RETRY_COUNT IS 'Current retry count';
COMMENT ON COLUMN FEP_REVERSAL.MAX_RETRY IS 'Maximum retry attempts';
COMMENT ON COLUMN FEP_REVERSAL.NEXT_RETRY_TIME IS 'Next retry timestamp';
COMMENT ON COLUMN FEP_REVERSAL.MANUAL_PROCESSING IS 'Flag for manual processing required (0=No, 1=Yes)';
COMMENT ON COLUMN FEP_REVERSAL.PROCESSED_BY IS 'Operator who processed manually';
COMMENT ON COLUMN FEP_REVERSAL.PROCESSED_TIME IS 'Manual processing timestamp';
COMMENT ON COLUMN FEP_REVERSAL.REVERSAL_DATE IS 'Reversal date in yyyyMMdd format for partitioning';

COMMIT;
