-- ============================================================
-- FEP_DAILY_LIMIT - Daily Transaction Limit Tracking
-- ============================================================
-- 記錄每個帳戶/卡片的日累計交易金額和次數，用於即時限額控管
-- ============================================================

-- Connect to FREEPDB1 as fep_user
CONNECT fep_user/fep_password@//localhost:1521/FREEPDB1

-- Create sequence
CREATE SEQUENCE SEQ_FEP_DAILY_LIMIT
    START WITH 1
    INCREMENT BY 50
    NOCACHE
    NOCYCLE;

-- Create table
CREATE TABLE FEP_DAILY_LIMIT (
    ID                  NUMBER(19) DEFAULT SEQ_FEP_DAILY_LIMIT.NEXTVAL PRIMARY KEY,
    ACCOUNT_NUMBER      VARCHAR2(32) NOT NULL,
    CARD_NUMBER         VARCHAR2(19),
    TRANSACTION_TYPE    VARCHAR2(30) NOT NULL,
    TRANSACTION_DATE    VARCHAR2(10) NOT NULL,
    DAILY_AMOUNT        NUMBER(15,2) DEFAULT 0 NOT NULL,
    DAILY_COUNT         NUMBER(10) DEFAULT 0 NOT NULL,
    DAILY_LIMIT_AMOUNT  NUMBER(15,2) NOT NULL,
    DAILY_LIMIT_COUNT   NUMBER(10) NOT NULL,
    BANK_CODE           VARCHAR2(10),
    CUSTOMER_TYPE       VARCHAR2(20),
    IS_DESIGNATED       NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP(6),
    VERSION             NUMBER(19) DEFAULT 0,
    CONSTRAINT UK_FEP_DAILY_LIMIT UNIQUE (ACCOUNT_NUMBER, TRANSACTION_TYPE, TRANSACTION_DATE)
);

-- Create indexes
CREATE INDEX IDX_FEP_DAILY_LIMIT_ACCT ON FEP_DAILY_LIMIT(ACCOUNT_NUMBER);
CREATE INDEX IDX_FEP_DAILY_LIMIT_CARD ON FEP_DAILY_LIMIT(CARD_NUMBER);
CREATE INDEX IDX_FEP_DAILY_LIMIT_DATE ON FEP_DAILY_LIMIT(TRANSACTION_DATE);
CREATE INDEX IDX_FEP_DAILY_LIMIT_ACCT_DATE ON FEP_DAILY_LIMIT(ACCOUNT_NUMBER, TRANSACTION_DATE);

-- Add comments
COMMENT ON TABLE FEP_DAILY_LIMIT IS 'Daily transaction limit tracking for accounts and cards';
COMMENT ON COLUMN FEP_DAILY_LIMIT.ACCOUNT_NUMBER IS 'Account number';
COMMENT ON COLUMN FEP_DAILY_LIMIT.CARD_NUMBER IS 'Card number (optional)';
COMMENT ON COLUMN FEP_DAILY_LIMIT.TRANSACTION_TYPE IS 'Transaction type: INTERBANK_TRANSFER, INTERBANK_WITHDRAWAL, INTERBANK_DEPOSIT, DESIGNATED_TRANSFER, NON_DESIGNATED_TRANSFER, BILL_PAYMENT, MOBILE_PAYMENT, ALL';
COMMENT ON COLUMN FEP_DAILY_LIMIT.TRANSACTION_DATE IS 'Transaction date in yyyyMMdd format';
COMMENT ON COLUMN FEP_DAILY_LIMIT.DAILY_AMOUNT IS 'Daily accumulated amount';
COMMENT ON COLUMN FEP_DAILY_LIMIT.DAILY_COUNT IS 'Daily transaction count';
COMMENT ON COLUMN FEP_DAILY_LIMIT.DAILY_LIMIT_AMOUNT IS 'Daily amount limit';
COMMENT ON COLUMN FEP_DAILY_LIMIT.DAILY_LIMIT_COUNT IS 'Daily count limit';
COMMENT ON COLUMN FEP_DAILY_LIMIT.BANK_CODE IS 'Bank code';
COMMENT ON COLUMN FEP_DAILY_LIMIT.CUSTOMER_TYPE IS 'Customer type: PERSONAL, CORPORATE';
COMMENT ON COLUMN FEP_DAILY_LIMIT.IS_DESIGNATED IS 'Whether designated account (0=No, 1=Yes)';

COMMIT;
