-- ============================================================
-- FEP_CARD_BLACKLIST - Card Blacklist Management
-- ============================================================
-- 記錄被列入黑名單的卡片資訊（掛失卡、偽卡、風險卡等）
-- ============================================================

-- Connect to FREEPDB1 as fep_user
CONNECT fep_user/fep_password@//localhost:1521/FREEPDB1

-- Create sequence
CREATE SEQUENCE SEQ_FEP_CARD_BLACKLIST
    START WITH 1
    INCREMENT BY 50
    NOCACHE
    NOCYCLE;

-- Create table
CREATE TABLE FEP_CARD_BLACKLIST (
    ID                      NUMBER(19) DEFAULT SEQ_FEP_CARD_BLACKLIST.NEXTVAL PRIMARY KEY,
    CARD_NUMBER             VARCHAR2(19) NOT NULL,
    CARD_NUMBER_MASKED      VARCHAR2(19),
    BLACKLIST_TYPE          VARCHAR2(30) NOT NULL,
    STATUS                  VARCHAR2(20) NOT NULL,
    ISSUER_BANK_CODE        VARCHAR2(10),
    REASON                  VARCHAR2(500),
    SOURCE                  VARCHAR2(50),
    FISC_NOTIFICATION_NO    VARCHAR2(30),
    EFFECTIVE_DATE          TIMESTAMP(6) NOT NULL,
    EXPIRY_DATE             TIMESTAMP(6),
    CREATED_BY              VARCHAR2(50),
    CREATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY              VARCHAR2(50),
    UPDATED_AT              TIMESTAMP(6),
    VERSION                 NUMBER(19) DEFAULT 0
);

-- Create indexes
CREATE INDEX IDX_FEP_CARD_BL_CARD_NUM ON FEP_CARD_BLACKLIST(CARD_NUMBER);
CREATE INDEX IDX_FEP_CARD_BL_STATUS ON FEP_CARD_BLACKLIST(STATUS);
CREATE INDEX IDX_FEP_CARD_BL_TYPE ON FEP_CARD_BLACKLIST(BLACKLIST_TYPE);
CREATE INDEX IDX_FEP_CARD_BL_ISSUER ON FEP_CARD_BLACKLIST(ISSUER_BANK_CODE, STATUS);
CREATE INDEX IDX_FEP_CARD_BL_FISC_NO ON FEP_CARD_BLACKLIST(FISC_NOTIFICATION_NO);
CREATE INDEX IDX_FEP_CARD_BL_EFF_EXP ON FEP_CARD_BLACKLIST(STATUS, EFFECTIVE_DATE, EXPIRY_DATE);

-- Add comments
COMMENT ON TABLE FEP_CARD_BLACKLIST IS 'Card blacklist for lost, stolen, counterfeit, and high-risk cards';
COMMENT ON COLUMN FEP_CARD_BLACKLIST.CARD_NUMBER IS 'Card number';
COMMENT ON COLUMN FEP_CARD_BLACKLIST.CARD_NUMBER_MASKED IS 'Masked card number for display (e.g., 1234****5678)';
COMMENT ON COLUMN FEP_CARD_BLACKLIST.BLACKLIST_TYPE IS 'Blacklist type: LOST, STOLEN, COUNTERFEIT, FRAUD, OVERDUE, OTHER_RISK, DECEASED, SYSTEM_DETECTED';
COMMENT ON COLUMN FEP_CARD_BLACKLIST.STATUS IS 'Status: ACTIVE, INACTIVE, PENDING_REVIEW, RELEASED';
COMMENT ON COLUMN FEP_CARD_BLACKLIST.ISSUER_BANK_CODE IS 'Issuing bank code';
COMMENT ON COLUMN FEP_CARD_BLACKLIST.REASON IS 'Reason description';
COMMENT ON COLUMN FEP_CARD_BLACKLIST.SOURCE IS 'Source: FISC notification, Bank notification, System detection';
COMMENT ON COLUMN FEP_CARD_BLACKLIST.FISC_NOTIFICATION_NO IS 'FISC notification number if applicable';
COMMENT ON COLUMN FEP_CARD_BLACKLIST.EFFECTIVE_DATE IS 'Effective date';
COMMENT ON COLUMN FEP_CARD_BLACKLIST.EXPIRY_DATE IS 'Expiry date (null means permanent)';
COMMENT ON COLUMN FEP_CARD_BLACKLIST.CREATED_BY IS 'Created by user';
COMMENT ON COLUMN FEP_CARD_BLACKLIST.UPDATED_BY IS 'Last updated by user';

COMMIT;
