-- ============================================================
-- FEP_ACCOUNT_BLACKLIST - Account Blacklist Management
-- ============================================================
-- 記錄被列入黑名單的帳號資訊（警示帳戶、凍結帳戶、詐欺帳戶等）
-- ============================================================

-- Connect to FREEPDB1 as fep_user
CONNECT fep_user/fep_password@//localhost:1521/FREEPDB1

-- Create sequence
CREATE SEQUENCE SEQ_FEP_ACCOUNT_BLACKLIST
    START WITH 1
    INCREMENT BY 50
    NOCACHE
    NOCYCLE;

-- Create table
CREATE TABLE FEP_ACCOUNT_BLACKLIST (
    ID                      NUMBER(19) DEFAULT SEQ_FEP_ACCOUNT_BLACKLIST.NEXTVAL PRIMARY KEY,
    ACCOUNT_NUMBER          VARCHAR2(32) NOT NULL,
    BANK_CODE               VARCHAR2(10) NOT NULL,
    BLACKLIST_TYPE          VARCHAR2(30) NOT NULL,
    STATUS                  VARCHAR2(20) NOT NULL,
    RESTRICTION_DIRECTION   VARCHAR2(20) NOT NULL,
    ACCOUNT_NAME            VARCHAR2(100),
    ID_NUMBER               VARCHAR2(20),
    REASON                  VARCHAR2(500),
    SOURCE                  VARCHAR2(50),
    NOTIFICATION_NO         VARCHAR2(50),
    EFFECTIVE_DATE          TIMESTAMP(6) NOT NULL,
    EXPIRY_DATE             TIMESTAMP(6),
    CREATED_BY              VARCHAR2(50),
    CREATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY              VARCHAR2(50),
    UPDATED_AT              TIMESTAMP(6),
    VERSION                 NUMBER(19) DEFAULT 0
);

-- Create indexes
CREATE INDEX IDX_FEP_ACCT_BL_ACCT_NUM ON FEP_ACCOUNT_BLACKLIST(ACCOUNT_NUMBER);
CREATE INDEX IDX_FEP_ACCT_BL_BANK_CODE ON FEP_ACCOUNT_BLACKLIST(BANK_CODE);
CREATE INDEX IDX_FEP_ACCT_BL_STATUS ON FEP_ACCOUNT_BLACKLIST(STATUS);
CREATE INDEX IDX_FEP_ACCT_BL_TYPE ON FEP_ACCOUNT_BLACKLIST(BLACKLIST_TYPE);
CREATE INDEX IDX_FEP_ACCT_BL_ACCT_BANK ON FEP_ACCOUNT_BLACKLIST(ACCOUNT_NUMBER, BANK_CODE, STATUS);
CREATE INDEX IDX_FEP_ACCT_BL_ID_NUM ON FEP_ACCOUNT_BLACKLIST(ID_NUMBER, STATUS);
CREATE INDEX IDX_FEP_ACCT_BL_NOTIF_NO ON FEP_ACCOUNT_BLACKLIST(NOTIFICATION_NO);
CREATE INDEX IDX_FEP_ACCT_BL_EFF_EXP ON FEP_ACCOUNT_BLACKLIST(STATUS, EFFECTIVE_DATE, EXPIRY_DATE);

-- Add comments
COMMENT ON TABLE FEP_ACCOUNT_BLACKLIST IS 'Account blacklist for alert accounts, frozen accounts, and fraud accounts';
COMMENT ON COLUMN FEP_ACCOUNT_BLACKLIST.ACCOUNT_NUMBER IS 'Account number';
COMMENT ON COLUMN FEP_ACCOUNT_BLACKLIST.BANK_CODE IS 'Bank code';
COMMENT ON COLUMN FEP_ACCOUNT_BLACKLIST.BLACKLIST_TYPE IS 'Blacklist type: ALERT_ACCOUNT, DERIVED_ALERT, COURT_FROZEN, FRAUD, AML_SUSPICIOUS, BANK_FROZEN, ABNORMAL_STATUS, OTHER_RISK';
COMMENT ON COLUMN FEP_ACCOUNT_BLACKLIST.STATUS IS 'Status: ACTIVE, INACTIVE, PENDING_REVIEW, RELEASED';
COMMENT ON COLUMN FEP_ACCOUNT_BLACKLIST.RESTRICTION_DIRECTION IS 'Restriction direction: INBOUND, OUTBOUND, BOTH';
COMMENT ON COLUMN FEP_ACCOUNT_BLACKLIST.ACCOUNT_NAME IS 'Account holder name (optional)';
COMMENT ON COLUMN FEP_ACCOUNT_BLACKLIST.ID_NUMBER IS 'ID number or business registration number (optional)';
COMMENT ON COLUMN FEP_ACCOUNT_BLACKLIST.REASON IS 'Reason description';
COMMENT ON COLUMN FEP_ACCOUNT_BLACKLIST.SOURCE IS 'Source: Alert account notification (165), Court order, Bank internal';
COMMENT ON COLUMN FEP_ACCOUNT_BLACKLIST.NOTIFICATION_NO IS 'Notification number (e.g., alert account notification number)';
COMMENT ON COLUMN FEP_ACCOUNT_BLACKLIST.EFFECTIVE_DATE IS 'Effective date';
COMMENT ON COLUMN FEP_ACCOUNT_BLACKLIST.EXPIRY_DATE IS 'Expiry date (null means permanent)';
COMMENT ON COLUMN FEP_ACCOUNT_BLACKLIST.CREATED_BY IS 'Created by user';
COMMENT ON COLUMN FEP_ACCOUNT_BLACKLIST.UPDATED_BY IS 'Last updated by user';

COMMIT;
