-- ============================================================
-- FEP_BANK_CODE - Bank Code Reference Data
-- ============================================================
-- 記錄財金公司核定的銀行代碼資訊，用於交易驗證和路由
-- ============================================================

-- Connect to FREEPDB1 as fep_user
CONNECT fep_user/fep_password@//localhost:1521/FREEPDB1

-- Create sequence
CREATE SEQUENCE SEQ_FEP_BANK_CODE
    START WITH 1
    INCREMENT BY 50
    NOCACHE
    NOCYCLE;

-- Create table
CREATE TABLE FEP_BANK_CODE (
    ID                      NUMBER(19) DEFAULT SEQ_FEP_BANK_CODE.NEXTVAL PRIMARY KEY,
    BANK_CODE               VARCHAR2(10) NOT NULL,
    HEAD_OFFICE_CODE        VARCHAR2(3),
    BRANCH_CODE             VARCHAR2(4),
    BANK_NAME_ZH            VARCHAR2(100) NOT NULL,
    BANK_NAME_EN            VARCHAR2(100),
    SHORT_NAME              VARCHAR2(50),
    SWIFT_CODE              VARCHAR2(11),
    INSTITUTION_TYPE        VARCHAR2(30) NOT NULL,
    STATUS                  VARCHAR2(20) NOT NULL,
    SUPPORT_TRANSFER        NUMBER(1) DEFAULT 1 NOT NULL,
    SUPPORT_WITHDRAWAL      NUMBER(1) DEFAULT 1 NOT NULL,
    SUPPORT_DEPOSIT         NUMBER(1) DEFAULT 0 NOT NULL,
    SUPPORT_BALANCE_INQUIRY NUMBER(1) DEFAULT 1 NOT NULL,
    SUPPORT_TAIWAN_PAY      NUMBER(1) DEFAULT 0 NOT NULL,
    CONTACT_PHONE           VARCHAR2(20),
    CONTACT_ADDRESS         VARCHAR2(200),
    EFFECTIVE_DATE          TIMESTAMP(6) NOT NULL,
    EXPIRY_DATE             TIMESTAMP(6),
    CREATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP(6),
    VERSION                 NUMBER(19) DEFAULT 0,
    CONSTRAINT UK_FEP_BANK_CODE UNIQUE (BANK_CODE)
);

-- Create indexes
CREATE INDEX IDX_FEP_BANK_CODE_STATUS ON FEP_BANK_CODE(STATUS);
CREATE INDEX IDX_FEP_BANK_CODE_TYPE ON FEP_BANK_CODE(INSTITUTION_TYPE);
CREATE INDEX IDX_FEP_BANK_CODE_HEAD ON FEP_BANK_CODE(HEAD_OFFICE_CODE);
CREATE INDEX IDX_FEP_BANK_CODE_SWIFT ON FEP_BANK_CODE(SWIFT_CODE);
CREATE INDEX IDX_FEP_BANK_CODE_EFF_EXP ON FEP_BANK_CODE(STATUS, EFFECTIVE_DATE, EXPIRY_DATE);

-- Add comments
COMMENT ON TABLE FEP_BANK_CODE IS 'Bank code reference data from FISC';
COMMENT ON COLUMN FEP_BANK_CODE.BANK_CODE IS 'Bank code (3-digit or 7-digit)';
COMMENT ON COLUMN FEP_BANK_CODE.HEAD_OFFICE_CODE IS 'Head office code (3 digits)';
COMMENT ON COLUMN FEP_BANK_CODE.BRANCH_CODE IS 'Branch code (4 digits, if applicable)';
COMMENT ON COLUMN FEP_BANK_CODE.BANK_NAME_ZH IS 'Bank name in Chinese';
COMMENT ON COLUMN FEP_BANK_CODE.BANK_NAME_EN IS 'Bank name in English';
COMMENT ON COLUMN FEP_BANK_CODE.SHORT_NAME IS 'Short name';
COMMENT ON COLUMN FEP_BANK_CODE.SWIFT_CODE IS 'SWIFT/BIC code';
COMMENT ON COLUMN FEP_BANK_CODE.INSTITUTION_TYPE IS 'Institution type: BANK, CREDIT_UNION, CREDIT_COOPERATIVE, POST_OFFICE, SECURITIES, E_PAYMENT, OTHER';
COMMENT ON COLUMN FEP_BANK_CODE.STATUS IS 'Status: ACTIVE, SUSPENDED, CLOSED, TESTING';
COMMENT ON COLUMN FEP_BANK_CODE.SUPPORT_TRANSFER IS 'Support interbank transfer (0=No, 1=Yes)';
COMMENT ON COLUMN FEP_BANK_CODE.SUPPORT_WITHDRAWAL IS 'Support interbank withdrawal (0=No, 1=Yes)';
COMMENT ON COLUMN FEP_BANK_CODE.SUPPORT_DEPOSIT IS 'Support interbank deposit (0=No, 1=Yes)';
COMMENT ON COLUMN FEP_BANK_CODE.SUPPORT_BALANCE_INQUIRY IS 'Support balance inquiry (0=No, 1=Yes)';
COMMENT ON COLUMN FEP_BANK_CODE.SUPPORT_TAIWAN_PAY IS 'Support Taiwan Pay (0=No, 1=Yes)';
COMMENT ON COLUMN FEP_BANK_CODE.CONTACT_PHONE IS 'Contact phone number';
COMMENT ON COLUMN FEP_BANK_CODE.CONTACT_ADDRESS IS 'Contact address';
COMMENT ON COLUMN FEP_BANK_CODE.EFFECTIVE_DATE IS 'Effective date';
COMMENT ON COLUMN FEP_BANK_CODE.EXPIRY_DATE IS 'Expiry date (null means permanent)';

-- Insert sample data (Taiwan major banks)
INSERT INTO FEP_BANK_CODE (BANK_CODE, HEAD_OFFICE_CODE, BANK_NAME_ZH, BANK_NAME_EN, SHORT_NAME, SWIFT_CODE, INSTITUTION_TYPE, STATUS, EFFECTIVE_DATE)
VALUES ('004', '004', '臺灣銀行', 'Bank of Taiwan', '臺銀', 'BKTWTWTP', 'BANK', 'ACTIVE', SYSTIMESTAMP);

INSERT INTO FEP_BANK_CODE (BANK_CODE, HEAD_OFFICE_CODE, BANK_NAME_ZH, BANK_NAME_EN, SHORT_NAME, SWIFT_CODE, INSTITUTION_TYPE, STATUS, EFFECTIVE_DATE)
VALUES ('005', '005', '臺灣土地銀行', 'Land Bank of Taiwan', '土銀', 'LABORTWT', 'BANK', 'ACTIVE', SYSTIMESTAMP);

INSERT INTO FEP_BANK_CODE (BANK_CODE, HEAD_OFFICE_CODE, BANK_NAME_ZH, BANK_NAME_EN, SHORT_NAME, SWIFT_CODE, INSTITUTION_TYPE, STATUS, EFFECTIVE_DATE)
VALUES ('006', '006', '合作金庫商業銀行', 'Taiwan Cooperative Bank', '合庫', 'TACBTWTP', 'BANK', 'ACTIVE', SYSTIMESTAMP);

INSERT INTO FEP_BANK_CODE (BANK_CODE, HEAD_OFFICE_CODE, BANK_NAME_ZH, BANK_NAME_EN, SHORT_NAME, SWIFT_CODE, INSTITUTION_TYPE, STATUS, EFFECTIVE_DATE)
VALUES ('007', '007', '第一商業銀行', 'First Commercial Bank', '一銀', 'FCBKTWTP', 'BANK', 'ACTIVE', SYSTIMESTAMP);

INSERT INTO FEP_BANK_CODE (BANK_CODE, HEAD_OFFICE_CODE, BANK_NAME_ZH, BANK_NAME_EN, SHORT_NAME, SWIFT_CODE, INSTITUTION_TYPE, STATUS, EFFECTIVE_DATE)
VALUES ('008', '008', '華南商業銀行', 'Hua Nan Commercial Bank', '華銀', 'HNBKTWTP', 'BANK', 'ACTIVE', SYSTIMESTAMP);

INSERT INTO FEP_BANK_CODE (BANK_CODE, HEAD_OFFICE_CODE, BANK_NAME_ZH, BANK_NAME_EN, SHORT_NAME, SWIFT_CODE, INSTITUTION_TYPE, STATUS, EFFECTIVE_DATE)
VALUES ('009', '009', '彰化商業銀行', 'Chang Hwa Commercial Bank', '彰銀', 'CCBCTWTP', 'BANK', 'ACTIVE', SYSTIMESTAMP);

INSERT INTO FEP_BANK_CODE (BANK_CODE, HEAD_OFFICE_CODE, BANK_NAME_ZH, BANK_NAME_EN, SHORT_NAME, SWIFT_CODE, INSTITUTION_TYPE, STATUS, EFFECTIVE_DATE)
VALUES ('011', '011', '上海商業儲蓄銀行', 'Shanghai Commercial & Savings Bank', '上海商銀', 'SCSBTWTP', 'BANK', 'ACTIVE', SYSTIMESTAMP);

INSERT INTO FEP_BANK_CODE (BANK_CODE, HEAD_OFFICE_CODE, BANK_NAME_ZH, BANK_NAME_EN, SHORT_NAME, SWIFT_CODE, INSTITUTION_TYPE, STATUS, EFFECTIVE_DATE)
VALUES ('012', '012', '台北富邦商業銀行', 'Taipei Fubon Commercial Bank', '富邦', 'TABORTWT', 'BANK', 'ACTIVE', SYSTIMESTAMP);

INSERT INTO FEP_BANK_CODE (BANK_CODE, HEAD_OFFICE_CODE, BANK_NAME_ZH, BANK_NAME_EN, SHORT_NAME, SWIFT_CODE, INSTITUTION_TYPE, STATUS, EFFECTIVE_DATE)
VALUES ('013', '013', '國泰世華商業銀行', 'Cathay United Bank', '國泰世華', 'UWCBTWTP', 'BANK', 'ACTIVE', SYSTIMESTAMP);

INSERT INTO FEP_BANK_CODE (BANK_CODE, HEAD_OFFICE_CODE, BANK_NAME_ZH, BANK_NAME_EN, SHORT_NAME, SWIFT_CODE, INSTITUTION_TYPE, STATUS, EFFECTIVE_DATE)
VALUES ('017', '017', '兆豐國際商業銀行', 'Mega International Commercial Bank', '兆豐', 'ICBCTWTP', 'BANK', 'ACTIVE', SYSTIMESTAMP);

INSERT INTO FEP_BANK_CODE (BANK_CODE, HEAD_OFFICE_CODE, BANK_NAME_ZH, BANK_NAME_EN, SHORT_NAME, SWIFT_CODE, INSTITUTION_TYPE, STATUS, EFFECTIVE_DATE)
VALUES ('700', '700', '中華郵政', 'Chunghwa Post', '郵局', 'PABORTWT', 'POST_OFFICE', 'ACTIVE', SYSTIMESTAMP);

INSERT INTO FEP_BANK_CODE (BANK_CODE, HEAD_OFFICE_CODE, BANK_NAME_ZH, BANK_NAME_EN, SHORT_NAME, SWIFT_CODE, INSTITUTION_TYPE, STATUS, EFFECTIVE_DATE)
VALUES ('808', '808', '玉山商業銀行', 'E.SUN Commercial Bank', '玉山', 'ESUNTWTP', 'BANK', 'ACTIVE', SYSTIMESTAMP);

INSERT INTO FEP_BANK_CODE (BANK_CODE, HEAD_OFFICE_CODE, BANK_NAME_ZH, BANK_NAME_EN, SHORT_NAME, SWIFT_CODE, INSTITUTION_TYPE, STATUS, EFFECTIVE_DATE)
VALUES ('812', '812', '台新國際商業銀行', 'Taishin International Bank', '台新', 'TSIBTWTP', 'BANK', 'ACTIVE', SYSTIMESTAMP);

INSERT INTO FEP_BANK_CODE (BANK_CODE, HEAD_OFFICE_CODE, BANK_NAME_ZH, BANK_NAME_EN, SHORT_NAME, SWIFT_CODE, INSTITUTION_TYPE, STATUS, EFFECTIVE_DATE)
VALUES ('822', '822', '中國信託商業銀行', 'CTBC Bank', '中信', 'CTCBTWTP', 'BANK', 'ACTIVE', SYSTIMESTAMP);

COMMIT;
