-- ============================================================
-- FEP System Oracle Database Schema
-- Version: 1.0.0
-- Description: Tables for FEP transaction and settlement system
-- ============================================================

-- ============================================================
-- 1. FEP_TRANSACTION - Transaction Records
-- ============================================================
CREATE TABLE FEP_TRANSACTION (
    ID                      NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRANSACTION_ID          VARCHAR2(64) NOT NULL,
    TRANSACTION_TYPE        VARCHAR2(32) NOT NULL,
    PROCESSING_CODE         VARCHAR2(6),
    MASKED_PAN              VARCHAR2(19),
    PAN                     VARCHAR2(64),           -- Encrypted PAN (3DES encrypted hex string)
    PAN_HASH                VARCHAR2(64),           -- SHA-256 hash for searching
    AMOUNT                  NUMBER(18,2),
    CURRENCY_CODE           VARCHAR2(3) DEFAULT '901',
    SOURCE_ACCOUNT          VARCHAR2(32),
    DESTINATION_ACCOUNT     VARCHAR2(32),
    DESTINATION_BANK_CODE   VARCHAR2(7),
    TERMINAL_ID             VARCHAR2(16),
    MERCHANT_ID             VARCHAR2(15),
    ACQUIRING_BANK_CODE     VARCHAR2(7),
    STAN                    VARCHAR2(6),
    RRN                     VARCHAR2(12),
    CHANNEL                 VARCHAR2(16),
    STATUS                  VARCHAR2(32) NOT NULL,
    RESPONSE_CODE           VARCHAR2(4),
    AUTHORIZATION_CODE      VARCHAR2(6),
    HOST_REFERENCE_NUMBER   VARCHAR2(32),
    ORIGINAL_TRANSACTION_ID VARCHAR2(64),
    REQUEST_TIME            TIMESTAMP(6),
    TRANSACTION_TIME        TIMESTAMP(6),
    RESPONSE_TIME           TIMESTAMP(6),
    PROCESSING_TIME_MS      NUMBER(10),
    ERROR_DETAILS           VARCHAR2(500),
    CREATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    TRANSACTION_DATE        VARCHAR2(10) NOT NULL,

    CONSTRAINT UK_FEP_TXN_ID UNIQUE (TRANSACTION_ID)
);

-- Indexes for FEP_TRANSACTION
CREATE INDEX IDX_FEP_TXN_RRN_STAN ON FEP_TRANSACTION(RRN, STAN);
CREATE INDEX IDX_FEP_TXN_MASKED_PAN ON FEP_TRANSACTION(MASKED_PAN, REQUEST_TIME);
CREATE INDEX IDX_FEP_TXN_TERMINAL ON FEP_TRANSACTION(TERMINAL_ID, REQUEST_TIME);
CREATE INDEX IDX_FEP_TXN_STATUS ON FEP_TRANSACTION(STATUS, TRANSACTION_DATE);
CREATE INDEX IDX_FEP_TXN_RRN_STAN_TERM ON FEP_TRANSACTION(RRN, STAN, TERMINAL_ID);
CREATE INDEX IDX_FEP_TXN_ORIGINAL ON FEP_TRANSACTION(ORIGINAL_TRANSACTION_ID);
CREATE INDEX IDX_FEP_TXN_DATE ON FEP_TRANSACTION(TRANSACTION_DATE);

COMMENT ON TABLE FEP_TRANSACTION IS 'FEP transaction records for FISC interbank operations';
COMMENT ON COLUMN FEP_TRANSACTION.TRANSACTION_ID IS 'Unique transaction identifier';
COMMENT ON COLUMN FEP_TRANSACTION.STAN IS 'System Trace Audit Number (ISO 8583 Field 11)';
COMMENT ON COLUMN FEP_TRANSACTION.RRN IS 'Retrieval Reference Number (ISO 8583 Field 37)';
COMMENT ON COLUMN FEP_TRANSACTION.TRANSACTION_DATE IS 'Transaction date in YYYY-MM-DD format for partitioning';

-- ============================================================
-- 2. FEP_SCHEDULED_TRANSFER - Scheduled Transfers
-- ============================================================
CREATE TABLE FEP_SCHEDULED_TRANSFER (
    SCHEDULE_ID             VARCHAR2(32) PRIMARY KEY,
    SOURCE_ACCOUNT          VARCHAR2(32) NOT NULL,
    DESTINATION_ACCOUNT     VARCHAR2(32) NOT NULL,
    DESTINATION_BANK_CODE   VARCHAR2(7) NOT NULL,
    AMOUNT                  NUMBER(18,2) NOT NULL,
    CURRENCY_CODE           VARCHAR2(3) DEFAULT '901',
    SCHEDULED_DATE          DATE NOT NULL,
    RECURRENCE_TYPE         VARCHAR2(10) DEFAULT 'ONE_TIME',
    END_DATE                DATE,
    REMAINING_EXECUTIONS    NUMBER(5),
    MEMO                    VARCHAR2(200),
    STATUS                  VARCHAR2(20) NOT NULL,
    CUSTOMER_ID             VARCHAR2(32) NOT NULL,
    CHANNEL                 VARCHAR2(16),
    CREATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP(6),
    LAST_EXECUTED_AT        TIMESTAMP(6),
    LAST_EXECUTION_RESULT   VARCHAR2(500),
    SUCCESSFUL_EXECUTIONS   NUMBER(10) DEFAULT 0,
    FAILED_EXECUTIONS       NUMBER(10) DEFAULT 0
);

-- Indexes for FEP_SCHEDULED_TRANSFER
CREATE INDEX IDX_SCH_TXF_CUSTOMER ON FEP_SCHEDULED_TRANSFER(CUSTOMER_ID);
CREATE INDEX IDX_SCH_TXF_STATUS_DATE ON FEP_SCHEDULED_TRANSFER(STATUS, SCHEDULED_DATE);
CREATE INDEX IDX_SCH_TXF_READY ON FEP_SCHEDULED_TRANSFER(SCHEDULED_DATE, STATUS);

COMMENT ON TABLE FEP_SCHEDULED_TRANSFER IS 'Scheduled transfer records (預約轉帳)';
COMMENT ON COLUMN FEP_SCHEDULED_TRANSFER.RECURRENCE_TYPE IS 'ONE_TIME, DAILY, WEEKLY, MONTHLY';
COMMENT ON COLUMN FEP_SCHEDULED_TRANSFER.STATUS IS 'PENDING, ACTIVE, COMPLETED, FAILED, CANCELLED, SUSPENDED';

-- ============================================================
-- 3. FEP_SETTLEMENT_FILE - Settlement Files
-- ============================================================
CREATE TABLE FEP_SETTLEMENT_FILE (
    FILE_ID                 VARCHAR2(32) PRIMARY KEY,
    FILE_NAME               VARCHAR2(255) NOT NULL,
    SETTLEMENT_DATE         DATE NOT NULL,
    FILE_TYPE               VARCHAR2(20) NOT NULL,
    SOURCE                  VARCHAR2(32),
    BANK_CODE               VARCHAR2(7),
    PROCESSING_STATUS       VARCHAR2(40) NOT NULL,
    RECEIVED_AT             TIMESTAMP(6),
    PROCESSING_STARTED_AT   TIMESTAMP(6),
    PROCESSING_COMPLETED_AT TIMESTAMP(6),
    ERROR_MESSAGE           VARCHAR2(1000),
    CHECKSUM                VARCHAR2(64),
    FILE_SIZE_BYTES         NUMBER(15),
    -- Header fields
    HEADER_VERSION          VARCHAR2(10),
    HEADER_CREATION_DATE    DATE,
    HEADER_CREATING_BANK    VARCHAR2(7),
    HEADER_RECEIVING_BANK   VARCHAR2(7),
    HEADER_FILE_TYPE        VARCHAR2(20),
    HEADER_RAW              CLOB,
    -- Trailer fields
    TRAILER_RECORD_COUNT    NUMBER(10),
    TRAILER_TOTAL_AMOUNT    NUMBER(18,2),
    TRAILER_DEBIT_AMOUNT    NUMBER(18,2),
    TRAILER_CREDIT_AMOUNT   NUMBER(18,2),
    TRAILER_DEBIT_COUNT     NUMBER(10),
    TRAILER_CREDIT_COUNT    NUMBER(10),
    TRAILER_CHECKSUM        VARCHAR2(64),
    TRAILER_RAW             CLOB,
    CREATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

-- Indexes for FEP_SETTLEMENT_FILE
CREATE INDEX IDX_STLMT_FILE_DATE ON FEP_SETTLEMENT_FILE(SETTLEMENT_DATE);
CREATE INDEX IDX_STLMT_FILE_STATUS ON FEP_SETTLEMENT_FILE(PROCESSING_STATUS);
CREATE INDEX IDX_STLMT_FILE_DATE_RANGE ON FEP_SETTLEMENT_FILE(SETTLEMENT_DATE, PROCESSING_STATUS);

COMMENT ON TABLE FEP_SETTLEMENT_FILE IS 'Settlement files received from FISC';
COMMENT ON COLUMN FEP_SETTLEMENT_FILE.FILE_TYPE IS 'DAILY, MONTHLY, AD_HOC';
COMMENT ON COLUMN FEP_SETTLEMENT_FILE.PROCESSING_STATUS IS 'RECEIVED, VALIDATING, PARSING, RECONCILING, COMPLETED, FAILED';

-- ============================================================
-- 4. FEP_SETTLEMENT_RECORD - Settlement Records
-- ============================================================
CREATE TABLE FEP_SETTLEMENT_RECORD (
    SEQUENCE_NUMBER         NUMBER(15) NOT NULL,
    FILE_ID                 VARCHAR2(32) NOT NULL,
    SETTLEMENT_DATE         DATE NOT NULL,
    TRANSACTION_REF_NO      VARCHAR2(64) NOT NULL,
    STAN                    VARCHAR2(6),
    RRN                     VARCHAR2(12),
    TRANSACTION_TYPE        VARCHAR2(32),
    TRANSACTION_CODE        VARCHAR2(10),
    ACQUIRING_BANK_CODE     VARCHAR2(7),
    ISSUING_BANK_CODE       VARCHAR2(7),
    CARD_NUMBER             VARCHAR2(64),           -- Encrypted card number
    AMOUNT                  NUMBER(18,2),
    CURRENCY_CODE           VARCHAR2(3),
    FEE_AMOUNT              NUMBER(18,2),
    NET_AMOUNT              NUMBER(18,2),
    TRANSACTION_DATE_TIME   TIMESTAMP(6),
    STATUS                  VARCHAR2(32) NOT NULL,
    TERMINAL_ID             VARCHAR2(16),
    MERCHANT_ID             VARCHAR2(15),
    AUTH_CODE               VARCHAR2(6),
    RESPONSE_CODE           VARCHAR2(4),
    IS_REVERSAL             NUMBER(1) DEFAULT 0,
    ORIGINAL_TRANSACTION_REF VARCHAR2(64),
    CHANNEL                 VARCHAR2(16),
    FROM_ACCOUNT            VARCHAR2(32),
    TO_ACCOUNT              VARCHAR2(32),
    RECORD_HASH             VARCHAR2(64),
    RAW_DATA                CLOB,
    NOTES                   VARCHAR2(500),
    MATCHED_TRANSACTION_ID  VARCHAR2(64),
    MATCHED_AT              TIMESTAMP(6),

    CONSTRAINT PK_STLMT_REC PRIMARY KEY (FILE_ID, SEQUENCE_NUMBER),
    CONSTRAINT FK_STLMT_REC_FILE FOREIGN KEY (FILE_ID)
        REFERENCES FEP_SETTLEMENT_FILE(FILE_ID) ON DELETE CASCADE
);

-- Indexes for FEP_SETTLEMENT_RECORD
CREATE INDEX IDX_STLMT_REC_REF ON FEP_SETTLEMENT_RECORD(TRANSACTION_REF_NO);
CREATE INDEX IDX_STLMT_REC_STATUS ON FEP_SETTLEMENT_RECORD(STATUS);
CREATE INDEX IDX_STLMT_REC_DATE ON FEP_SETTLEMENT_RECORD(SETTLEMENT_DATE, STATUS);
CREATE INDEX IDX_STLMT_REC_MATCHED ON FEP_SETTLEMENT_RECORD(MATCHED_TRANSACTION_ID);
CREATE INDEX IDX_STLMT_REC_RRN_STAN ON FEP_SETTLEMENT_RECORD(RRN, STAN);

COMMENT ON TABLE FEP_SETTLEMENT_RECORD IS 'Individual settlement records from FISC files';
COMMENT ON COLUMN FEP_SETTLEMENT_RECORD.STATUS IS 'PENDING, MATCHED, AMOUNT_MISMATCH, NOT_FOUND, DUPLICATE, etc.';

-- ============================================================
-- 5. FEP_DISCREPANCY - Discrepancy Records
-- ============================================================
CREATE TABLE FEP_DISCREPANCY (
    DISCREPANCY_ID          VARCHAR2(32) PRIMARY KEY,
    DISCREPANCY_TYPE        VARCHAR2(32) NOT NULL,
    SETTLEMENT_DATE         DATE NOT NULL,
    SETTLEMENT_FILE_ID      VARCHAR2(32),
    SETTLEMENT_RECORD_REF   VARCHAR2(64),
    INTERNAL_TRANSACTION_REF VARCHAR2(64),
    SETTLEMENT_AMOUNT       NUMBER(18,2),
    INTERNAL_AMOUNT         NUMBER(18,2),
    DIFFERENCE_AMOUNT       NUMBER(18,2),
    CURRENCY_CODE           VARCHAR2(3),
    CARD_NUMBER             VARCHAR2(64),           -- Encrypted card number
    TRANSACTION_TYPE        VARCHAR2(32),
    STATUS                  VARCHAR2(32) NOT NULL,
    PRIORITY                VARCHAR2(20) NOT NULL,
    DESCRIPTION             VARCHAR2(1000),
    ROOT_CAUSE              VARCHAR2(1000),
    RESOLUTION_NOTES        VARCHAR2(2000),
    RESOLUTION_ACTION       VARCHAR2(32),
    ASSIGNED_TO             VARCHAR2(64),
    CREATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP(6),
    RESOLVED_AT             TIMESTAMP(6),
    RESOLVED_BY             VARCHAR2(64),
    INVESTIGATION_NOTES     CLOB,
    RELATED_DISCREPANCIES   VARCHAR2(1000),

    CONSTRAINT FK_DISC_FILE FOREIGN KEY (SETTLEMENT_FILE_ID)
        REFERENCES FEP_SETTLEMENT_FILE(FILE_ID) ON DELETE SET NULL
);

-- Indexes for FEP_DISCREPANCY
CREATE INDEX IDX_DISC_DATE ON FEP_DISCREPANCY(SETTLEMENT_DATE);
CREATE INDEX IDX_DISC_STATUS ON FEP_DISCREPANCY(STATUS);
CREATE INDEX IDX_DISC_TYPE ON FEP_DISCREPANCY(DISCREPANCY_TYPE);
CREATE INDEX IDX_DISC_PRIORITY ON FEP_DISCREPANCY(PRIORITY);
CREATE INDEX IDX_DISC_ASSIGNED ON FEP_DISCREPANCY(ASSIGNED_TO, STATUS);

COMMENT ON TABLE FEP_DISCREPANCY IS 'Discrepancies found during settlement reconciliation';
COMMENT ON COLUMN FEP_DISCREPANCY.DISCREPANCY_TYPE IS 'AMOUNT_MISMATCH, MISSING_IN_SETTLEMENT, MISSING_IN_INTERNAL, DUPLICATE, STATUS_MISMATCH';
COMMENT ON COLUMN FEP_DISCREPANCY.STATUS IS 'OPEN, INVESTIGATING, PENDING_APPROVAL, RESOLVED, WRITTEN_OFF, ESCALATED, CLOSED';
COMMENT ON COLUMN FEP_DISCREPANCY.PRIORITY IS 'HIGH, MEDIUM, LOW';
COMMENT ON COLUMN FEP_DISCREPANCY.INVESTIGATION_NOTES IS 'JSON array of investigation notes';

-- ============================================================
-- 6. FEP_CLEARING_RECORD - Clearing Records
-- ============================================================
CREATE TABLE FEP_CLEARING_RECORD (
    CLEARING_ID             VARCHAR2(32) PRIMARY KEY,
    SETTLEMENT_DATE         DATE NOT NULL,
    BATCH_NUMBER            VARCHAR2(20),
    OUR_BANK_CODE           VARCHAR2(7) NOT NULL,
    COUNTERPARTY_BANK_CODE  VARCHAR2(7) NOT NULL,
    TRANSACTION_CATEGORY    VARCHAR2(32),
    DEBIT_COUNT             NUMBER(10) DEFAULT 0,
    DEBIT_AMOUNT            NUMBER(18,2) DEFAULT 0,
    CREDIT_COUNT            NUMBER(10) DEFAULT 0,
    CREDIT_AMOUNT           NUMBER(18,2) DEFAULT 0,
    NET_AMOUNT              NUMBER(18,2),
    FEE_AMOUNT              NUMBER(18,2),
    CURRENCY_CODE           VARCHAR2(3) DEFAULT 'TWD',
    STATUS                  VARCHAR2(20) NOT NULL,
    CREATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONFIRMED_AT            TIMESTAMP(6),
    SETTLED_AT              TIMESTAMP(6),
    CONFIRMED_BY            VARCHAR2(64),
    NOTES                   VARCHAR2(500),
    SETTLEMENT_FILE_ID      VARCHAR2(32),

    CONSTRAINT FK_CLR_FILE FOREIGN KEY (SETTLEMENT_FILE_ID)
        REFERENCES FEP_SETTLEMENT_FILE(FILE_ID) ON DELETE SET NULL
);

-- Indexes for FEP_CLEARING_RECORD
CREATE INDEX IDX_CLR_DATE ON FEP_CLEARING_RECORD(SETTLEMENT_DATE);
CREATE INDEX IDX_CLR_STATUS ON FEP_CLEARING_RECORD(STATUS);
CREATE INDEX IDX_CLR_COUNTERPARTY ON FEP_CLEARING_RECORD(COUNTERPARTY_BANK_CODE);
CREATE INDEX IDX_CLR_OUR_BANK ON FEP_CLEARING_RECORD(OUR_BANK_CODE, SETTLEMENT_DATE);

COMMENT ON TABLE FEP_CLEARING_RECORD IS 'Net clearing amounts between banks';
COMMENT ON COLUMN FEP_CLEARING_RECORD.NET_AMOUNT IS 'Positive=we receive, Negative=we pay';
COMMENT ON COLUMN FEP_CLEARING_RECORD.STATUS IS 'PENDING, CALCULATED, CONFIRMED, SUBMITTED, SETTLING, SETTLED, FAILED, CANCELLED';

-- ============================================================
-- Grants (adjust schema owner as needed)
-- ============================================================
-- GRANT SELECT, INSERT, UPDATE, DELETE ON FEP_TRANSACTION TO FEP_APP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON FEP_SCHEDULED_TRANSFER TO FEP_APP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON FEP_SETTLEMENT_FILE TO FEP_APP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON FEP_SETTLEMENT_RECORD TO FEP_APP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON FEP_DISCREPANCY TO FEP_APP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON FEP_CLEARING_RECORD TO FEP_APP;
